### ISSUE TITLE
can we see outgoing data before ssl pinning

### ISSUE THREAD

**Issue by gaplan** [depoon/NetworkInterceptor#24]
Does the NetworkInterceptor code only work as sinifable?
Instagram, Facebook, Tinder does not sniffable now.
they all using ssl pinning.
how can i pass ssl pinning?
or can we see outgoing data before ssl pinning ?

**Comment by gaplan** [comment]
@depoon @StevenArmandLee

**Comment by StevenArmandLee** [comment]
It will work with certificate pining. The code is sandwiched in the middle of the request call and the request going out of the app. 

The demo working for twitter app here https://youtu.be/P55D0D63QZY

**Comment by gaplan** [comment]
Hi @StevenArmandLee 
yes it will work twitter but **tinder, instagram, facebook**. does not work .

**Comment by gaplan** [comment]
@depoon . Hi There.

**Comment by depoon** [comment]
@gaplan can u share your observations? what did you mean when it does not work

**Comment by gaplan** [comment]
Sure. 
Twitter works,
but instagram or tinder does not work.
I'm sending wetransfer  the code and ipa files I use.
https://we.tl/t-kgRZVElq2m

**Comment by depoon** [comment]
Will take a look tonite

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gaplan** [comment]
Thank you so much.

**Comment by gaplan** [comment]
@depoon , Hi again. 
Have you had a chance to look at the files?

**Comment by depoon** [comment]
@gaplan 

I observed this crash? is this the same issue you are facing? otherwise kindly share your crash log
``
Termination Description: DYLD, Symbol not found: _$s8RawValueSYTl | Referenced from: /var/containers/Bundle/Application/E0725CB7-D730-45E7-9018-50E597C72E41/Tinder.app/Dylibs/Gzip.framework/Gzip | Expected in: /private/var/containers/Bundle/Application/E0725CB7-D730-45E7-9018-50E597C72E41/Tinder.app/Frameworks/libswiftCore.dylib | in /var/containers/Bundle/Application/E0725CB7-D730-45E7-9018-50E597C72E41/Tinder.app/Dylibs/Gzip.framework/Gzip
``

This is not sufficient for me to debug. Can you send over your actual source code (Xcode Project) so that i can investigate?

**Comment by bryankeller** [comment]
@gaplan bump, please send your code, I also want to see this fixed

**Comment by depoon** [comment]
@gaplan @bryankeller 
The issue above is problem (or even app) specific that requires alot of trial and error. At the moment, i wont be able to give a general solution to it.

What brought most people here was my blog article and meetup presentation on binary injection. The issue described above falls in the domain of `binary/framework injection`, `patching` or even `hacking` and is out of scope on what this library can do.

Please direct all `binary injection` issues to https://github.com/depoon/iOSDylibInjectionDemo instead.

Meanwhile, i would recommend you to experiment with this pod with your working projects and observe the console log. You will find it useful to replay the same cURL requests on POSTMAN.

With that, I shall close this issue.
